### ISSUE TITLE
STATUS in critical

### ISSUE THREAD

**Issue by KevinMoreau3** [catinello/nagios-check-website#5]
Hello, 

I'm using your plugin, and when I try to check a fake website, the plugin don't return a CRITICAL status but a UNKNOW status. 
Is it possible to have this behavior? 

Thanks.

**Comment by catinello** [comment]
Hi Kevin. 

What is a fake website? Can you please post how your command line looks like? 

Thx

**Comment by KevinMoreau3** [comment]
I mean a website with no response.

For example, I have a server with a tomcat on 10.1.12.56.
Tomcat have a webapp with context /MascaretRecette.

When tomcat is running, I do the following command :
/usr/lib/nagios/plugins/check_website.sh -p 8081 -u /MascaretRecette 10.1.12.56

ð  HTTP OK: 51ms - http://10.1.12.56:8081/MascaretRecette|time=51ms;500;2000;0;



But when tomcat is stopped with the same command :

ð  HTTP Server issued an error response: 8 - http://10.1.12.56:8081/MascaretRecette

And on Centreon, the status is UNKNOW, and I would like CRITICAL.

Thanks.

[cid:image001.png@01D2A3B2.1CE1EC40]

    Kévin Moreau
    Analyste/Développeur





[id:image002.jpg@01D2262B.19EAE780]

kevin.moreau@trsb.net<mailto:kevin.moreau@trsb.net>


     Suivez-nous !


[id:image003.png@01D2262B.19EAE780]

02 49 62 10 75

       www.trsb.net<http://www.trsb.net/>


[id:image004.jpg@01D2262B.19EAE780]

06 01 30 58 94

[id:image005.png@01D2262B.19EAE780]<http://fr.linkedin.com/company/trsb>

[id:image006.png@01D2262B.19EAE780]<http://www.viadeo.com/fr/company/trsb>

[id:image007.png@01D2262B.19EAE780]<http://www.facebook.com/GroupeTRSb/>

[id:image008.png@01D2262B.19EAE780]<http://twitter.com/groupetrsb>    [id:image009.jpg@01D2262B.19EAE780] <https://www.youtube.com/watch?v=sy8ie54siKo&list=PLjToihhjFPcwMuQUImMLg98e7898ous4Z&nohtml5=False>

[id:image010.jpg@01D2262B.19EAE780]

32 boulevard Vincent Gâche - 44200 Nantes




De : Antonino Catinello <notifications@github.com>
Répondre à : catinello/nagios-check-website <reply@reply.github.com>
Date : mercredi 22 mars 2017 à 21:30
À : catinello/nagios-check-website <nagios-check-website@noreply.github.com>
Cc : Kevin MOREAU <Kevin.MOREAU@trsb.net>, Author <author@noreply.github.com>
Objet : Re: [catinello/nagios-check-website] STATUS in critical (#5)


Hi Kevin.

What is a fake website? Can you please post how your command line looks like?

Thx

**Comment by catinello** [comment]
You are right! If wget runs into any kind of error we're handling it and the check status is unknown. But since wget and the network communication is mandatory to our check it actually is an error. Therefore all known wget errors are supposed to be critical. Thank you for pointing that out.
